#+title: 10 Elektronska spinska resonanca
#+startup: entitiespretty nil

* Uvod
Za spektroskopijo z elektronsko spinsko resonanco se pogosto uporablja sinonim elektronske magnetne resonance. Magnetna resonančna spektroskopija se imenuje, ker merimo prehod med energijskimi nivoji prostih elektronov v magnetnem polju. Princip delovanja je podoben kot pri jedrski magnetni resonanci, le da so frekvence mnogo višje. Pri nižjih frekvencah in odgovarjajočem magnetnem polju vseeno pride do zanimivih pojavov.

Elektron je delec s spinom \( S = \frac{1}{2} \) in ima po klasični teoriji magnetni moment, katerega velikost je /Bohrov magneton/ \( \mu_B = e \hbar/ 2 m_e = 9.27 10^{-24} \mathrm{J} / \mathrm{T} \). V zunanjem magnetnem polju imamo dve možnosti projekcije vrtilne količine. Vzporedno z magnetnim poljem \( B_0 \), kjer je magnetno kvantno število \( m_s = \frac{1}{2} \) in nasprotno s poljem \( m_s = - \frac{1}{2} \). Med tema stanjema je energijska razlika \( \Delta E \):

\[ \Delta E = E_{\text{up}} - E_{\text{down}} = g \mu_B B_0
\]

kjer je \( g \) Landejev faktor in je za prost elektron (z upoštevkom relativističnih popravkov) enak \( 2.0023192 \). Landejev faktor je odvisen tudi od kemične vezave in elektronskega okolja. Prehode med tema dvema nivojema lahko vzbujamo z elektromagnetnih sevanjem, ki je dovolj energetično, ai. izpolnjuje pogoje

\[ \Delta E = g \mu_B B_0 = h \nu
\]

Tako smo dobili zvezo med frekvenco in resonančno vrednostjo magnetnega polja. Energijska razlika \( \Delta E \) je relativno majhna v primerjavi z vidno ali IR spektroskopijo, zato so signali precej šibki. Relativno populacijo obeh energijskih nivojev podaja Boltzmannova porazdelitev

\[ \frac{n_2}{n_1} = e ^{- \frac{\Delta E}{k_B T}} = e ^{- \frac{h \nu}{k_B T}}
\]

kjer je \( k_B \) Boltzmannova konstanta in \( T \) absolutna temperatura. Zaradi interakcij elektrona s kristalno mrežo, z drugimi elektroni ali jedri, resonančne črte niso ostre, ampak razširjene ali razcepljene.

** Eksperiment

V našem primeru imamo vzorec *DPPH* (2, 2-diphenil-1-pikrilhidrazil), ki se nahaja v tuljavi resonančnega regenerativnega oscilatorja. Ko zunanje magnetno polje \( B_0 \) doseže vrednosti, ki izpolnjuje resonančni pogoj, nastopi absorpcija visoko frekvenčnega valovanja in amplituda oscilacij oscilatorja pade. Oscilacije preko diode opazujem na osciloskopu.

Dodatno si olajšamo z modulacijo magnetnega polja. Amplituda modulacije je običajno manjša od širine črte, kar pomeni, da dobimo signal modulacijske, katerega amplituda je proporcianalna odvodu absorcpijske črte v odvisnosti od statične komponente polja.

Signal na osciloskopu je šibek in ne izstopa od šuma, zato uporabimo fazni detektor. Ta ima na voljo referenčni signal \( U_{ref} = U_0 \cos (\omega t + \phi) \), kar je v našem primeru napetosti, ki napaja modulacijske tuljave. Signal \( U_{sig} = A(t) \cos (\omega t) \) je usmerjen izhod regenerativnega oscilatorja delno prekrit s šumom in iste frekvence \( \omega \). Med njima je fazna razlika \( \phi \).

Fazni detektor napravi produkt obeh singalov kot analogni množilec

\[ U_{out} = U_{ref} U_{sig} = \frac{1}{2} A(t) \left[ \cos \phi + \cos (2\omega + \phi) \right]
\]
S tem smo dosegli, da je nosilna frekvenca signala \( A(t) \) enaka nič. Drugega člea pa se preprosto znebimo z RC filtrom.
* Potrebščine
- vzorec 
- refenerrativni oscilator 
- osciloskop
- modulacijske tuljave in njihov napajalec
- fazni detektor
* Naloge
 - z vzorcem DPPH kot merjencem določi \( g \) faktor prostega elektrona in razmerje \( B/ \nu \). 
 - izmeri širino absorcpijske črte
* Meritve

Vrednost \(  g = 1.96 \pm 0.04 \)
Vrednost diagonale:  [0.18667619023324855+/-0.0012247448713915891]

Vrednost za Delta B pri 80 v mT:  [0.12571021494856024+/-0.014838030418430835]
Vrednost B0 pri 80 MHz v m [2.8677642785140307+/-0.01881482361559623]
Vrednost nu/B0 v GHz / T pri 80:  [27.896295591439976+/-0.18302197464899134]

Vrednost za Delta B pri 85 v mT:  [0.1361860661942736+/-0.014842009360139954]
Vrednost B0 pri 85 MHz v m [3.0432347868797294+/-0.019966050266048238]
Vrednost nu/B0 v GHz / T pri 85:  [27.930805853843328+/-0.18324838952726832]

Vrednost za Delta B pri 90 v mT:  [0.1361860661942736+/-0.014842009360139954]
Vrednost B0 pri 90 MHz v m [3.23180010930257+/-0.021203189353101143]
Vrednost nu/B0 v GHz / T pri 90:  [27.848256994898797+/-0.1827068030962125]
