#+title: Sunkovna jedrska magnetna resonanca
#+startup: entitiespretty nil
#+startup: nolatexpreview
#+LATEX_HEADER: \usepackage{amsmath}

* Uvod

Jedro ima poleg vrtilne količine \(  \vec{\Gamma} \) tudi magnetni moment \(  \vec{\mu} \). Vrtilna količina in magnetni moment imata isto smer in sta povezana z enačbo

\begin{equation}
\label{eq:1}
\vec{\mu} = \gamma \vec{\Gamma}
\end{equation}

kjer je \(  \gamma \) giromagnetno razmerje, ki je odvisno od vrste jedra.

V magnetnem polju \(  \vec{B}_0 \), ki naj kaže vzdolž osi \(  z \), deluje na magnetni moment navor

\begin{equation}
\label{eq:2}
\vec{N} = \vec{\mu} \times \vec{B}_0 = \gamma \vec{\Gamma} \times \vec{B}_0
\end{equation}

Sprememba vrtilna količine je sorazmerna sunku navora, kar da enačbo

\begin{equation}
\label{eq:3}
\frac{\mathrm{d} \vec{\Gamma}}{\mathrm{dt}} = \vec{N} = \gamma \vec{\Gamma} \times \vec{B}_0
\end{equation}

Sprememba vrtilne količine je vedno pravokotna na sunek in na magnetno polje. Iz tega sledi, da magnetni moment precesira okoli smeri magnetnega polja z Larmorjevo frekvenco

\begin{equation}
\label{eq:4}
\omega_L = \gamma \left| \vec{B}_0 \right|
\end{equation}

Če v homogeno magnetno polje postavimo snov, ki ima neničelna jedra s spinom \(  \vec{\Gamma} \) in magnetnim momentom \(  \vec{\mu} \) se v njej pojavi magnetizacija, ki je magnetni moment na enoto volumna.

Tudi ta precesira okrog smeri magnetnega polja z Larmorjevo frekvenco, kadar ni vzporedna z njim.

Imamo še dodatno magnetno polje \(  \vec{B}_1 \), ki kaže v smeri \(  x \), pravokotno na smer statičnega polja, in oscilira z Larmorjevo frekvenco. Za kratek čas vključimo \(  \vec{B}_1 \) in kot med magnetizacijo in statičnim magnetnim poljem \(  \vec{B}_0 \) se poveča.

Velikost kota je odvisna od amplitude in časa trajanja polja \(  \vec{B}_1 \). Posebej zanimivi so sunki, ki spremenijo kot za \(  \pi \) ali \(  \frac{\pi}{2} \).

Dodatno magnetno polje povzročimo s tuljavico, ki je napajana s sunkovnim radiofrekvenčnim (RF) izvorom električnega izvora. Tako govorimo o sunkih \(  \pi \) in \(  \frac{\pi}{2} \).

Definiramo vrteči se sistem znotraj laboratorijskega, ki se vrti okoli smeri magnetnega polja z Larmorjevo frekvenco \(  \omega_L \):

\begin{align*}
  z ' &= z \\
x' &= x \cos \left( \omega_L t \right) + y \sin \left( \omega_L t \right) \\
y' &= y \cos \left( \omega_L t \right) - x \sin \left( \omega_L t \right)
\end{align*}

Dodatno magnetno polje tako zapišemo kot

\[ \vec{B}_1 = B_1 (\cos \left( \omega_L t \right), 0, 0)
\]

Prva komponenta se vrti skupaj z vrtečim se sistemom, ki smo ga definirali in je v njem statična vzdolž osi \(  x' \). Z vpeljavo vrtečega polja smo upoštevali statično magnetno polje \(  \vec{B}_0 \). To pomeni, da magnetizacija \(  \vec{M} \) precesira okoli osi \(  x' \) in ne več okoli \(  z \). Edino, kar je, je to, da se magnetizacija odkloni za nek kot od \(  z = z' \).

Sunek \(  \frac{\pi}{2} \) obrne polarizacijo v smer osi \(  y' \) in ne čuti nobenega zunanjega magnetnega polja. Ker je magnetizacija vsota magnetnih momentov posameznih jeder, ne ostane obrnjena vzdolž osi \(  y' \), ampak se s časom vrne v termodinamsko ravnovesno vrednost.

Projekcije magnetnim momentov se v ravnini \( x'y' \) prej povrnejo v ravnovesno stanje (aka raztresenost), kakor pa se njihova komponenta \(  z' \). Projekcija magnetizacije na ravnino \(  x'y' \) zato eksponento pada z razpadno konstanto \(  T_2 \), ki jo imenujemo spinsko-spinski relaksacijski čas.

Na čas \(  T_2 \) vpliva samo interakcija med magnetnimi momenti, zato tudi tako ime.

Poleg izgube fazne povezave se zmanjšuje tudi azimut posameznega magnetnega momenta. Projekcija na os \(  z' \) se zato povečuje s karakterističnim časom \(  T_1 \), ki ga imenujemo tudi spinsko-mrežni relaksacijski čas

\begin{equation}
\label{eq:6}
M_{z'} = M(1 - e^{-\frac{t}{T_1}})
\end{equation}

Če imamo nehomogeno magnetno polje, projekcija magnetizacije v ravnino \(  x'y' \) ne pada več eksponento s časom \(  T_2 \), ampak kot neka druga krivulja \(  T_2^{*} \), ki je odvisna od \(  T_2 \), nehomogenosti magnetnega polja in od oblike vzorca.

Ocenimo ga lahko kot

\[ T_2^{*} \approx \frac{\pi}{2} \frac{1}{\gamma \Delta B_z} \approx \frac{1}{\gamma \Delta B_z}
\]

Po sunku \(  \frac{\pi}{2} \) je magnetni moment obrnjen v smeri osi \(  y' \) in nato precesira okoli osi \(  z' \) z neko frekvenco \(  \omega \). V času \(  \tau \) se zavrti za kot \(  \phi = \omega \tau \) glede na os \(  y' \). S sunkom \(  \pi \) se magnetni moment zasuka v nasprotno smer \(  \pi - \omega \tau \). Po času \(  2\tau \) bodo magnetni momenti ponovno v smeri osi \(  -y' \), saj je \(  \phi(2\tau) = \pi - \omega \tau + \omega \tau \).

V merilni tuljavici se zato pojavi signal, ki ga imenujemo spinski odmev. Amplituda spinskega odmeva z večanjem razmaka med sunkoma pada kot

\[ e ^{-\frac{2\tau}{T_2}}
\]

širina pa je odvisna od tega, kako hitro se magnetni momenti spet zberejo nazaj v smeri \(  -y' \) in je enaka \(  T_2^{*} \).
* Potrebščine

- NMR spektrometer
- vzorci vode
- osciloskop
- napajalnik
- vodno hlajenje
- elektromagnet

* Naloge

- za vzorec vode s primešanimi paramagnetnimi ioni poišči signal proste precesije po sunku \(  \frac{\pi}{2} \) in signal spinskega odmeva po zaporedju sunkov \(  \frac{\pi}{2} \) in \(  \pi \). Z opazovanjem širine proste precesije in signala spinskega odmeva poišči takšno lego sonde, da bo magnetno polje v področju vzorca čimbolj homogeno. Iz obeh širin izračunaj \(  T_2^{*} \) in oceni nehomogenost magnetnega polja v vzorcu
- Z opazovanjem odvisnost signala proste precesije med dvema sunkoma \(  \frac{\pi}{2} \) določi relaksacijski čas \(  T_1 \) za vzorec vode s primešanimi paramagnetnimi ioni in za vzorec vodovodne vode
- Za vodo s primešanimi paramagnetnimi ioni poišči odvisnost višine signala spinskega odmeva od presledka \(  \tau \) med sunkoma \(  \frac{\pi}{2} \) in \(  \pi \) in določi spinsko-spinski relaksacijski čas \(  T_2 \).
* Meritve
